# Generated by Django 5.1.6 on 2025-02-25 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'cities',
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('duration_minutes', models.IntegerField()),
                ('total_stops', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_info', models.TextField(blank=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.airline')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('passenger_name', models.CharField(blank=True, max_length=100, null=True)),
                ('passenger_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('passenger_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('booking_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', '待确认'), ('confirmed', '已确认'), ('cancelled', '已取消')], default='pending', max_length=10)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flight')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='flights.city')),
                ('source_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='flights.city')),
            ],
            options={
                'unique_together': {('source_city', 'destination_city')},
            },
        ),
        migrations.AddField(
            model_name='flight',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.route'),
        ),
        migrations.CreateModel(
            name='TempBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('departure_date', models.DateField(null=True)),
                ('passenger_name', models.CharField(max_length=100, null=True)),
                ('passenger_phone', models.CharField(max_length=20, null=True)),
                ('passenger_email', models.EmailField(max_length=254, null=True)),
                ('preferred_time', models.CharField(max_length=20, null=True)),
                ('available_flights', models.CharField(max_length=200, null=True)),
                ('selected_flight_id', models.IntegerField(null=True)),
                ('booking_stage', models.CharField(choices=[('searching', '搜索航班'), ('selecting', '选择航班'), ('collecting_info', '收集信息'), ('confirming', '确认预订')], default='searching', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('destination_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_arrivals', to='flights.city')),
                ('source_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='temp_departures', to='flights.city')),
            ],
            options={
                'indexes': [models.Index(fields=['session_id'], name='flights_tem_session_d01fc0_idx'), models.Index(fields=['status'], name='flights_tem_status_a31696_idx')],
            },
        ),
    ]
