# Generated by Django 5.1.6 on 2025-02-26 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempbooking',
            name='modification_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tempbooking',
            name='booking_stage',
            field=models.CharField(choices=[('searching', '搜索航班'), ('selecting', '选择航班'), ('collecting_info', '收集信息'), ('confirming', '确认预订'), ('modifying', '修改订单')], default='searching', max_length=20),
        ),
        migrations.AddIndex(
            model_name='tempbooking',
            index=models.Index(fields=['booking_stage'], name='flights_tem_booking_157628_idx'),
        ),
        migrations.AddIndex(
            model_name='tempbooking',
            index=models.Index(fields=['modification_id'], name='flights_tem_modific_307fef_idx'),
        ),
    ]
